Spie/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Models;
using Spie.Data;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public CategoryController(ApplicationDbContext db)
        {
            dbContext = db;
        }
        public async Task<IActionResult> Index()
        {

            return View(await dbContext.Category.ToListAsync());
        }
        //GET for Create
        public IActionResult Create()
        {
            return View();
        }
        //POST CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Category.Add(category);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        // GET - EDIT

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Update(category);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST _ DELETE

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (ModelState.IsValid)
            {
                var cat = await dbContext.Category.FindAsync(id);
                if (cat == null)
                    return NotFound();
                dbContext.Category.Remove(cat);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return NotFound();
        }

        //Assigment 1:
        //Get Details
        public async Task<IActionResult>Details(int? id)
        {
            if (ModelState.IsValid)
            {
                var cat = await dbContext.Category.FindAsync(id);
                return View(cat);
            }
            return NotFound();
        }


    }
}

Spie/Areas/Admin/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Spice.Models;
using Spice.Models.ViewModels;
using Spie.Data;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoryController : Controller
    {

        private readonly ApplicationDbContext dbContext;

        [TempData]
        public string StatusMessage { get; set; }


        public SubCategoryController(ApplicationDbContext db)
        {
            dbContext = db;
        }

        //GET INDEX
        public async Task<IActionResult> Index()
        {
            var SubCategories = await dbContext.SubCategory.Include(cat=>cat.Category).ToListAsync();
            return View(SubCategories);
        }

        //GET CREATE

        public async Task<IActionResult> Create()
        {
            SubCategoryAndCategoryViewModel model = new SubCategoryAndCategoryViewModel()
            {
                CategoryList = await dbContext.Category.ToListAsync(),
                SubCategory = new SubCategory(),
                SubCategoryList = await dbContext.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync<String>()

            };
            return View(model);
            
        }

        //POST - CREATE

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubCategoryAndCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesSubCategoryExsist = dbContext.SubCategory.Include(c => c.Category).Where(s => s.Name == model.SubCategory.Name && s.Category.Id == model.SubCategory.CategoryId);
                if (doesSubCategoryExsist.Count() > 0)
                {
                    //Error
                    StatusMessage = "Error: Sub Category exists under " + doesSubCategoryExsist.First().Category.Name + " category. Please use another name ";
                }
                else
                {
                    dbContext.SubCategory.Add(model.SubCategory);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            SubCategoryAndCategoryViewModel viewModel = new SubCategoryAndCategoryViewModel()
            {
                CategoryList = await dbContext.Category.ToListAsync(),
                SubCategory = model.SubCategory,
                SubCategoryList = await dbContext.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage
            };
            return View(viewModel);

        }

        [ActionName("GetSubCategory")]
        public async Task<IActionResult>GetSubCategory(int id)
        {
            List<SubCategory> subCategories = new List<SubCategory>();
            subCategories = await(from subCategory in dbContext.SubCategory where subCategory.CategoryId == id
                             select subCategory).ToListAsync();
            return Json(new SelectList(subCategories, "Id", "Name"));

        }

        //GET EDIT
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var subCat = await dbContext.SubCategory.SingleOrDefaultAsync(m => m.Id == id);
            if (subCat == null)
            {
                return NotFound();
            }

            SubCategoryAndCategoryViewModel model = new SubCategoryAndCategoryViewModel()
            {
                CategoryList = await dbContext.Category.ToListAsync(),
                SubCategory = subCat,
                SubCategoryList = await dbContext.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).Distinct().ToListAsync<String>()

            };
            return View(model);

        }

        //POST - EDIT

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,SubCategoryAndCategoryViewModel model)
        {
           

            var subCat = await dbContext.SubCategory.SingleOrDefaultAsync(m => m.Id == id);
        

            if (ModelState.IsValid)
            {
                var doesSubCategoryExsist = dbContext.SubCategory.Include(c => c.Category).Where(s => s.Name == model.SubCategory.Name && s.Category.Id == model.SubCategory.CategoryId);
                if (doesSubCategoryExsist.Count() > 0)
                {
                    //Error
                    StatusMessage = "Error: Sub Category exists under " + doesSubCategoryExsist.First().Category.Name + " category. Please use another name ";
                }
                else
                {
                    var subCatFromDb = await dbContext.SubCategory.FindAsync(id);
                    subCatFromDb.Name = model.SubCategory.Name;

                     
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            SubCategoryAndCategoryViewModel viewModel = new SubCategoryAndCategoryViewModel()
            {
                CategoryList = await dbContext.Category.ToListAsync(),
                SubCategory = model.SubCategory,
                SubCategoryList = await dbContext.SubCategory.OrderBy(p => p.Name).Select(p => p.Name).ToListAsync(),
                StatusMessage = StatusMessage
            };
            viewModel.SubCategory.Id = id;
            return View(viewModel);

        }
        [HttpGet]
        public async Task<IActionResult>Details(int id)
        {
            if (ModelState.IsValid)
            {
                var subcat = await dbContext.SubCategory.FindAsync(id);
                SubCategoryNameAndCategoryNameViewModel viewModel = new SubCategoryNameAndCategoryNameViewModel()
                {
                    SubCategoryName = subcat.Name,
                    IdSubCategory = subcat.Id,
                    CategoryName = dbContext.Category.Where(x => x.Id == subcat.CategoryId).FirstOrDefault().Name

                };
                return View(viewModel);
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult>Delete(int id)
        {
            if (ModelState.IsValid)
            {
                var subcat = await dbContext.SubCategory.FindAsync(id);
                SubCategoryNameAndCategoryNameViewModel viewModel = new SubCategoryNameAndCategoryNameViewModel()
                {
                    SubCategoryName = subcat.Name,
                    IdSubCategory = subcat.Id,
                    CategoryName = dbContext.Category.Where(x => x.Id == subcat.CategoryId).FirstOrDefault().Name

                };
                return View(viewModel);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Delete(int? id)
        {
            var subCat = await dbContext.SubCategory.FirstOrDefaultAsync(x => x.Id == id);
            dbContext.SubCategory.Remove(subCat);
            await dbContext.SaveChangesAsync();
            return View("Index");
        }


    }
}

Spie/Views/Shared/_CreateBackToListButton.cshtml
<br />
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spie/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn-info"> <i class="fas fa-plus"></i>&nbsp;Create New</a>
</p>

Spie/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <a asp-action="Delete" class="btn btn-success form-control" asp-route-id="@Model">Delete</a>

    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
</div>

Spie/Views/Shared/_DetailsAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" asp-action="Details" readonly class="btn btn-danger form-control" value="Details" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
</div>

Spie/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row ">
    <div class="col-6">
        <input type="submit" asp-action="Edit" class="btn btn-info form-control" asp-route-id="@Model" value="Edit" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
</div>

Spie/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/2ac4c80f31.js" crossorigin="anonymous"></script>   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark    border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                <a class="dropdown-item">Menu Item</a>
                                <a class="dropdown-item">Coupons</a>
                                <a class="dropdown-item">Users</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40;">
        <div class="container">
            &copy; 2020 - "Spice" Kujawski Szymon MVC project
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Spie/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spie/Views/Shared/_TableButtonPartial.cshtml
@model int
<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-info-square"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>